name: workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      continue-on-error: true

    - name: Setup
      shell: pwsh
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

        net user administrator ${{ secrets.ADMIN_PASSWORD }} /add
        net localgroup administrators administrator /add
      continue-on-error: true

    - name: Set Administrator UI Preferences
      shell: pwsh
      run: |
        # --- Define Paths ---
        $adminProfileDir = "C:\Users\Administrator"
        $userHivePath = Join-Path $adminProfileDir "NTUSER.DAT"
        $defaultUserHivePath = "C:\Users\Default\NTUSER.DAT"
        $regMountPath = "HKLM\AdministratorHive"
        
        # --- THE GRANDMA-SAVING FIX: SEED THE USER PROFILE ---
        # A user's NTUSER.DAT hive does not exist until first login. We must create it
        # by copying the template from the 'Default' user profile.
        if (-not (Test-Path $userHivePath)) {
            Write-Host "Administrator profile hive not found at '$userHivePath'."
            Write-Host "Seeding profile from default user template at '$defaultUserHivePath'."
            
            # Ensure the parent directory exists before copying.
            New-Item -Path $adminProfileDir -ItemType Directory -Force | Out-Null
            Copy-Item -Path $defaultUserHivePath -Destination $userHivePath -Force
            
            Write-Host "Administrator profile hive has been created successfully."
        } else {
            Write-Host "Administrator profile hive already exists."
        }
        
        # We MUST use a try/finally block to ensure the hive is always unloaded.
        try {
            Write-Host "Loading Administrator user registry hive from '$userHivePath' into '$regMountPath'"
            reg.exe load $regMountPath $userHivePath
            
            # --- CRITICAL ERROR CHECK ---
            # Verify reg.exe succeeded before proceeding.
            if ($LASTEXITCODE -ne 0) {
                throw "FATAL: 'reg.exe load' failed with exit code $LASTEXITCODE. Cannot modify registry."
            }
            Write-Host "Hive loaded successfully."

            # Define target registry paths *inside* the mounted hive
            $themePath = "Registry::$regMountPath\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize"
            $colorsPath = "Registry::$regMountPath\Control Panel\Colors"
            $desktopPath = "Registry::$regMountPath\Control Panel\Desktop"
            
            # --- Create Keys if they don't exist ---
            Write-Host "Ensuring required registry key paths exist..."
            New-Item -Path $themePath -Force | Out-Null
            
            # --- Set Dark Mode ---
            Write-Host "Setting Apps & System to Dark Mode..."
            Set-ItemProperty -Path $themePath -Name "AppsUseLightTheme" -Value 0 -Type DWord -Force
            Set-ItemProperty -Path $themePath -Name "SystemUsesLightTheme" -Value 0 -Type DWord -Force
            
            # --- Set Solid Black Background ---
            Write-Host "Setting solid background color to black and disabling wallpaper..."
            Set-ItemProperty -Path $colorsPath -Name "Background" -Value "0 0 0" -Type String -Force
            Set-ItemProperty -Path $desktopPath -Name "Wallpaper" -Value "" -Type String -Force
            
            Write-Host "UI preferences have been successfully set for the Administrator user."
        }
        catch {
            # Catch any PowerShell errors and provide detailed info.
            Write-Error "A fatal error occurred while modifying the registry."
            Write-Error $_.Exception.Message
            throw # Re-throw the error to ensure the GitHub Actions step fails.
        }
        finally {
            # This block ALWAYS runs.
            Write-Host "Unloading Administrator user registry hive from '$regMountPath'."
            
            # Force garbage collection to release any latent file handles.
            [gc]::Collect()
            
            reg.exe unload $regMountPath
            # Check for unload errors, but don't throw, as the main error is more important.
            if ($LASTEXITCODE -ne 0) {
                Write-Warning "'reg.exe unload' failed with exit code $LASTEXITCODE. The hive might still be loaded."
            } else {
                Write-Host "Hive unloaded successfully."
            }
        }
      continue-on-error: true

    - name: Add 
      shell: pwsh
      run: |
        $WshShell = New-Object -comObject WScript.Shell
        $Shortcut = $WshShell.CreateShortcut("C:\Users\Public\Desktop\Chrome_Reddit.lnk")
        $Shortcut.TargetPath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
        $Shortcut.Arguments = "--no-first-run https://reddit.com https://guerrillamail.com"
        $Shortcut.Save()
      continue-on-error: true

    - name: Install
      shell: pwsh
      run: |
        Expand-Archive nssm-2.24.zip -DestinationPath .\nssm
        $nssmDir = Get-ChildItem -Path .\nssm -Directory | Select-Object -First 1
        $nssmExe = Get-ChildItem -Path $nssmDir.FullName -Filter nssm.exe -Recurse | Select-Object -First 1
        Copy-Item -Path $nssmExe.FullName -Destination .\nssm.exe
      continue-on-error: true

    - name: Install cloudflared
      shell: pwsh
      run: |
        .\nssm.exe install cloudflared $PWD\cloudflared.exe "tunnel --url rdp://localhost:3389"
        .\nssm.exe set cloudflared AppDirectory $PWD
        .\nssm.exe set cloudflared AppExit Default Restart
        .\nssm.exe set cloudflared AppStdout $PWD\cloudflared-log.log
        .\nssm.exe set cloudflared AppStderr $PWD\cloudflared-log.log
        .\nssm.exe start cloudflared
      continue-on-error: true

    - name: Wait
      shell: pwsh
      run: |
        $found = $false
        while (-not $found) {
          Start-Sleep -Milliseconds 100
          $logContent = Get-Content "$PWD\cloudflared-log.log" -Raw
          if ($logContent -match "(https:\/\/[a-zA-Z0-9\-]+\.trycloudflare\.com)") {
            $tunnelURL = $matches[1]
            $found = $true
          }
        }

        # Get GitHub Actions run ID
        $run_id = $env:GITHUB_RUN_ID

        # Send tunnel URL to the server
        $server_url = "${{ secrets.SERVER_URL }}/update-run/$run_id"
        $server_secret = "${{ secrets.SERVER_SECRET }}"
        $headers = @{
          "Authorization" = "Bearer $server_secret"
          "Content-Type"  = "application/json"
        }
        $body = @{
          "tunnel_url" = $tunnelURL
        } | ConvertTo-Json

        Invoke-RestMethod -Uri $server_url -Method POST -Headers $headers -Body $body

      continue-on-error: true

    - name: Download
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://1111-releases.cloudflareclient.com/win/latest" -OutFile "Cloudflare_WARP_Release-x64.msi"
        msiexec /i "Cloudflare_WARP_Release-x64.msi" /qn
      continue-on-error: true

    - name: Extract
      shell: pwsh
      run: |
        $ipAddress = ""
        while (-not $ipAddress) {
          Start-Sleep -Milliseconds 100
          $logLines = Get-Content "$PWD\cloudflared-log.log"
          foreach ($line in $logLines) {
            if ($line -match "ip=(\d{1,3}(?:\.\d{1,3}){3})") {
              $ipAddress = $matches[1]
              break
            }
          }
        }

        Add-Content -Path $env:GITHUB_ENV -Value "TUNNEL_IP=$ipAddress"

      continue-on-error: true

    - name: Create
      shell: pwsh
      run: |
        $batchContent = @"
        @echo off
        set "warpCliPath=C:\Program Files\Cloudflare\Cloudflare WARP\warp-cli.exe"
        "%warpCliPath%" registration new
        "%warpCliPath%" mode warp
        "%warpCliPath%" tunnel ip add $env:TUNNEL_IP
        "%warpCliPath%" connect
        pause
        "@
        
        Set-Content -Path "C:\Users\Public\Desktop\Cloudflare_WARP.bat" -Value $batchContent
      continue-on-error: true

    - name: Add 2
      shell: pwsh
      run: |
        $WshShell   = New-Object -ComObject WScript.Shell
        $linkPath    = "C:\Users\Public\Desktop\Cloudflare_WARP_Installer.lnk"
        $targetMsI   = "$PWD\Cloudflare_WARP_Release-x64.msi"
        $Shortcut    = $WshShell.CreateShortcut($linkPath)
        $Shortcut.TargetPath = $targetMsI
        $Shortcut.Description = "Cloudflare WARP Installer"
        $Shortcut.Save()
      continue-on-error: true

    - name: Keep
      shell: pwsh
      run: |
        while ($true) {
          Start-Sleep -Seconds 36000
        }
      continue-on-error: true
